server:
  port: 8000
  
spring:
  application:
    name: apigateway-service
    
  cloud:
    gateway:
      routes:
      
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user-service/users
        - Method= POST
        
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user-service/login
        - Method= POST
        
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user-service/health_check
        - Method= GET
        
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user-service/**
        - Method=GET, POST, PUT, DELETE
        filters:
        - name: AuthorizationFilter
#          args:
#            num1: 1
#            num2: 2
        

        
      - id: catalog-service #순서 2번
        uri: lb://CATALOG-SERVICE #순서 3번
        predicates:
        - Path=/catalog-service/** #순서 1번   
        - Method=GET, POST, PUT, DELETE
        
      - id: order-service #순서 2번
        uri: lb://ORDER-SERVICE #순서 3번
        predicates:
        - Path=/order-service/** #순서 1번   
        - Method=GET, POST, PUT, DELETE
      
      
      
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true 
    fetch-registry: true 
    service-url:
      defaultZone: http://localhost:8761/eureka 
